spring.application.name=janani
spring.datasource.url=jdbc:mysql://localhost:3306/Todo
spring.datasource.username=root
spring.datasource.password=Varshini@2008
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
