spring.application.name=janani

spring.datasource.url=jdbc:postgresql://zephyr.proxy.rlwy.net:35439/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=duLpkBzMPgXSXKrJlxhppENtgdGhtivT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect